### ISSUE TITLE
why "show databases" trigger [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde0b22]

### ISSUE THREAD

**Issue by chengfangang** [blastrain/vitess-sqlparser#31]
COM_QUERY: show databases
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde0b22]

goroutine 26 [running]:
github.com/blastrain/vitess-sqlparser/sqlparser.convertTiDBStmtToVitessShow(0xc0003280b0, 0x1, 0x1, 0xc0005a6100, 0x0, 0x0)
        /root/software/sqlaudit/vendor/github.com/blastrain/vitess-sqlparser/sqlparser/type_converter.go:92 +0x62
github.com/blastrain/vitess-sqlparser/sqlparser.Parse(0xc000594490, 0xe, 0x4d35e6, 0x6139b690, 0x2c3ce2aa, 0x62d137f69c)
        /root/software/sqlaudit/vendor/github.com/blastrain/vitess-sqlparser/sqlparser/ast.go:63 +0x3e7

**Comment by nickolasgregory** [comment]
For me this also occurs for `SHOW TABLE STATUS FROM table_name` queries.
